Feat/add application codes to all memos
KTH/kurs-pm-data-api pull request #168
Opened 2023-02-06 14:31 UTC by Rao-Sabahat-Ali

1. Added new get requests to get all memos and memofiles from both coursememos and memofiles collections.
2. Added new Put service to update application codes in both coursememos and memofiles collections.

Note: Please do not merge this PR. It is only for review to update both collections with application codes.

2023-02-08 11:53 UTC, lenaar requested changes
It look like one parameter if off if to compare with prev code, should be checked, otherwise looks good to me. Ready to be tested on all test data

2023-02-08 11:53 UTC, lenaar commented on swagger.json
> +            "name": "status",
this status is a duplicate of the one on line 289

2023-02-08 11:53 UTC, lenaar commented on server/lib/dbSeveralDocument.js
> +    await dbMigratedPdfs.map(({ applicationCodes }) => finalObj.usedRoundsThisSemester.push(...applicationCodes))
here it looks like it should destruct dbMigratedPdfs `applicationCode` (singular) if to compare with prev code

2023-02-27 10:50 UTC, lenaar approved these changes

2025-04-01 12:29 UTC, closed without merging

2025-04-01 12:29 UTC, belanglos commented
This is not needed anymore! 🚀